
// Generated by Cadence Genus(TM) Synthesis Solution 20.12-s150_1
// Generated on: Jan 18 2024 13:33:38 IST (Jan 18 2024 08:03:38 UTC)

// Verification Directory fv/counter 

module counter(count, rst, clk, SDI, SDO, scan_enable);
  input rst, clk, SDI, scan_enable;
  output [7:0] count;
  output SDO;
  wire rst, clk, SDI, scan_enable;
  wire [7:0] count;
  wire SDO;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  assign SDO = 1'b0;
  SDFFRHQX1 \count_reg[7] (.RN (rst), .CK (clk), .D (n_0), .SI
       (count[7]), .SE (n_14), .Q (count[7]));
  DFFRHQX1 \count_reg[6] (.RN (rst), .CK (clk), .D (n_15), .Q
       (count[6]));
  OA21X1 g188__2398(.A0 (count[6]), .A1 (n_12), .B0 (n_14), .Y (n_15));
  DFFRHQX1 \count_reg[5] (.RN (rst), .CK (clk), .D (n_13), .Q
       (count[5]));
  AOI2BB1XL g191__5107(.A0N (count[5]), .A1N (n_10), .B0 (n_12), .Y
       (n_13));
  NAND2XL g190__6260(.A (count[6]), .B (n_12), .Y (n_14));
  DFFRHQX1 \count_reg[3] (.RN (rst), .CK (clk), .D (n_7), .Q
       (count[3]));
  AOI21XL g194__4319(.A0 (n_9), .A1 (n_8), .B0 (n_10), .Y (n_11));
  AND2X1 g193__8428(.A (count[5]), .B (n_10), .Y (n_12));
  NOR2XL g196__5526(.A (n_9), .B (n_8), .Y (n_10));
  OA21X1 g197__6783(.A0 (count[3]), .A1 (n_5), .B0 (n_8), .Y (n_7));
  DFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (n_2), .Q
       (count[1]));
  AOI21XL g200__3680(.A0 (n_4), .A1 (n_3), .B0 (n_5), .Y (n_6));
  NAND2XL g199__1617(.A (count[3]), .B (n_5), .Y (n_8));
  NOR2XL g202__2802(.A (n_4), .B (n_3), .Y (n_5));
  OA21X1 g203__1705(.A0 (count[0]), .A1 (count[1]), .B0 (n_3), .Y
       (n_2));
  NAND2XL g205__5122(.A (count[0]), .B (count[1]), .Y (n_3));
  INVXL g206(.A (count[7]), .Y (n_0));
  DFFRX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_1), .Q (count[0]),
       .QN (n_1));
  DFFRX1 \count_reg[4] (.RN (rst), .CK (clk), .D (n_11), .Q (count[4]),
       .QN (n_9));
  DFFRX1 \count_reg[2] (.RN (rst), .CK (clk), .D (n_6), .Q (count[2]),
       .QN (n_4));
endmodule

